# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  esbuild-aarch64-darwin = {
    pname = "esbuild-aarch64-darwin";
    version = "0.19.4";
    src = fetchTarball {
      url = "https://registry.npmjs.org/@esbuild/darwin-arm64/-/darwin-arm64-0.19.4.tgz";
      sha256 = "sha256-mtCCgWZi2wdbgz0gRYLP/GZfgJ/UKLnPTBvc5pxpk9g=";
    };
  };
  esbuild-aarch64-linux = {
    pname = "esbuild-aarch64-linux";
    version = "0.19.4";
    src = fetchTarball {
      url = "https://registry.npmjs.org/@esbuild/linux-arm64/-/linux-arm64-0.19.4.tgz";
      sha256 = "sha256-0UNPha4R8O8cCDiddB6755asI8eFzZT/wvwrN7xEKPo=";
    };
  };
  esbuild-x86_64-darwin = {
    pname = "esbuild-x86_64-darwin";
    version = "0.19.4";
    src = fetchTarball {
      url = "https://registry.npmjs.org/@esbuild/darwin-x64/-/darwin-x64-0.19.4.tgz";
      sha256 = "sha256-6vGfZgKyZw0DHkov07UYsIIGIy8DyeDvcn6qZSPTDxU=";
    };
  };
  esbuild-x86_64-linux = {
    pname = "esbuild-x86_64-linux";
    version = "0.19.4";
    src = fetchTarball {
      url = "https://registry.npmjs.org/@esbuild/linux-x64/-/linux-x64-0.19.4.tgz";
      sha256 = "sha256-Cf8siblPU9rrTajm88VYibOSIimM2Of0kQudINeOrew=";
    };
  };
}
